# Dockerfile para C1 - Ubuntu 16.10
FROM ubuntu:16.10


RUN sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y openssh-client && \
    apt-get clean

CMD ["bash"]